name: ${project.name}
author: Tocoolmh58
version: ${project.version}
main: de.tobiaswild.timer.Main
api-version: 1.18
description: ${project.description}
commands:
  timer:
    description: controll the timer